{
    "port": 7000,
    "editor": "nano",
    "routes": [
        {
            "name": "product-api",
            "path": "/product",
            "dest": "localhost:18081"
        },
        {
            "name": "user-api",
            "path": "/user",
            "dest": "localhost:18080"
        }
    ]
}









